### ISSUE TITLE
package doesn't work/do anything; or is inconsistant

### ISSUE THREAD

**Issue by robjac** [in19farkt/css-to-jss#2]
literally have tried to use this on multiple occasions : usually copying css from Invision.

Gif below:
![csstojssdoesn twork](https://user-images.githubusercontent.com/1988220/50708954-1d740f80-1034-11e9-9e63-73f178347863.gif)

I have also tried this:

![withconst](https://user-images.githubusercontent.com/1988220/50709039-82c80080-1034-11e9-804e-bf1027f3767e.gif)

using the latest vscode; in a .js file (jsx);

**Comment by robjac** [comment]
Inconsistencies happen once in a while, where 1 css rule is successfully converted.

**Comment by in19farkt** [comment]
Thank you for the issue. This happened because you are using tabs. In the near future, I will try to fix it.

**Comment by in19farkt** [comment]
Fixed in 1.0.5

**Comment by robjac** [comment]
Unfortunately Invision outputs tabs on copy :( It's very annoying. I appreciate the update and the fix. thanks again.
