### ISSUE TITLE
Trailing spaces break conversion

### ISSUE THREAD

**Issue by nickakey** [in19farkt/css-to-jss#8]
Hello!

Sometimes when I copy classes from the Chrome inspector, the last class has 4 or 5 trailing spaces with it. 

Running the extension on it does NOT convert the bottom value ( the one with trailing spaces )

Here's an example of an exact paste from chrome inspector.

```
        left: 120px;
    top: 350px;    
```
(I don't know of a way to encode spaces into MD - but to reproduce it, just add 4 - 5 spaces after the last semi-colon;

**Comment by in19farkt** [comment]
Fixed in 1.0.7

**Comment by nickakey** [comment]
Fantastic! Thank you :)
